export const magicWords = [
  "you are my cupcake and my sweetest comfort",
  "you are my forever sunshine in every storm",
  "i love you my sweetest sweetheart",
  "my darling you are my safest place",
  "under moonlight and daylight i choose you",
  "you are my beloved destiny",
  "your heartbeat feels like home to me",
  "with you passion feels peaceful",
  "i choose you in this life and in eternity",
  "you are my greatest treasure",
  "my angel you make ordinary days magical",
  "good morning my honey my always",
  "you are my snowflake one of a kind",
  "you are my starlight in the darkest nights",
  "our love is my favorite romance story",
  "come here for a forever cuddle",
  "every promise i make begins with you",
  "my devotion to you is quiet but endless",
  "in every lifetime i will find you",
  "home is wherever you are",
  "you are my calm and my chaos",
  "with you even silence feels warm",
  "i fell for you and never stood back up",
  "your smile is my daily sunshine",
  "you are my once in a lifetime love",
  "forever looks good on us",
  "my heart recognized you instantly",
  "every version of my future has you in it",
  "you are my favorite notification",
  "i love you more than yesterday and less than tomorrow",
];
